### PR TITLE
Remove Data Type Coupling

### PR DESCRIPTION
**Pull request by AkoWu101**
Remove Generic Type on YfListAdapter as Data type coupling. Library users cannot be easy to switch different data list with different data structures. 

Add Features on YfListAdapter
- notifyAllDataSetChanged [Notice headers, footers and custom data set to update UI]
- notifyCustomDataSetChanged [Notice all custom data set to update UI]

### CODE REVIEW

**Comment by yefengjie** [comment]
there is some conflict in pull request

**Comment by AkoWu101** [comment]
Yes. I modify the core base class. Should have conflict

**Comment by yefengjie** [comment]
And I found that there is some params is missing in the library, when I try to solve the conflict

**Comment by AkoWu101** [comment]
which class miss params?

**Comment by yefengjie** [comment]
I got mData is missing in YfListAdapter

**Comment by AkoWu101** [comment]
Yes. mData is removed as this will cause Data Type Coupling. 

i added a abstract function getDataCount();
Child class should implement it. Also, Child class should hold mData individually.

**Pull request closed without merging**
