### PR TITLE
Add new feature to support multi-type data

### PR DESCRIPTION
**Pull request by AkoWu101**
Just give up UltimateRecyclerView, which is buggy. Your library is nice. Keep it simple =]

Just add a new function on your library XDD

### CODE REVIEW

**Comment by yefengjie** [comment]
ok, thanks for your contribution, I have already merged your code. Let's test for some days, then I will update it to jcenter.

**Comment by AkoWu101** [comment]
Hi,

I am updating the base adapter. I found that it exist Dependency Coupling with Type. 

Currently, To define a Adapter. Will be like this,

```
class CustomAdapter extends YfListAdatper<String>
```

If i switch different data structure and using the same adapter, it cannot handle it.
I think your intention is checking the dat list whether it is empty, if it is empty, then show empty view. Just check the Android spec, find that notify*\* functions. All of them is Final method. It seems there is no way to show empty view automatically. Need to show it manually.

**Comment by yefengjie** [comment]
Sorry I don't catch your meaning. Do you mean let the user to show empty view manually?

**Comment by AkoWu101** [comment]
Let me update my repository soon.

夜风 notifications@github.com 於 2015年10月24日 星期六寫道：

**Comment by AkoWu101** [comment]
Just update the Data Type coupling. i found that

https://github.com/Malinskiy/SuperRecyclerView https://github.com/Malinskiy/SuperRecyclerView

After take a look on this library, i wonder that Empty View, Loading View and Error View, switch to YfListRecyclerView.
As Library User do not need to handle obBindEmptyView, LoadingView, Error View at the same time.

**Comment by yefengjie** [comment]
Yeah, this library is separate from one project. EmptyView, LoadingView,
Error View always should be exits in common case, however Error View is not
 necessary.

2015-10-27 15:37 GMT+08:00 kw101 notifications@github.com:

> Just update the Data Type coupling. i found that
> 
> https://github.com/Malinskiy/SuperRecyclerView <
> https://github.com/Malinskiy/SuperRecyclerView>
> 
> After take a look on this library, i wonder that Empty View, Loading View
> and Error View, switch to YfListRecyclerView.
> As Library User do not need to handle obBindEmptyView, LoadingView, Error
> View at the same time.
>

**Pull request merged**
